---
name: Test

on:
  push:
    branches:
      - devel
  pull_request:


concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  setup_matrix:
    name: "Determine Ansible versions"
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.ansible.outputs.versions }}
    steps:
      - id: ansible
        uses: evgeni/ansible-version@v0

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    needs: setup_matrix
    strategy:
      fail-fast: false
      matrix:
        ansible: ${{ fromJSON(needs.setup_matrix.outputs.ansible) }}
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          pull-request-change-detection: false

  molecule:
    needs: setup_matrix
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.11"
        ansible: ${{ fromJSON(needs.setup_matrix.outputs.ansible) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Ansible
        run: pip install --upgrade https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz
      - name: Install dependencies
        run: pip install molecule molecule-plugins pytest pytest-ansible pytest-xdist
      - name: Run tests
        run: pytest -vv --molecule roles/

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install ansible-lint
      - name: Run ansible-lint
        run: ansible-lint -vv

  check:
    if: always()

    needs:
      - sanity
      - molecule
      - ansible-lint

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
